environment:
  matrix:
    - nodejs_version: 12
      platform: x64
    - nodejs_version: 12
      platform: x86
    # electron
    - nodejs_version: 12
      platform: x64
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 8.3.4
      TOOLSET_ARGS: --dist-url=https://electronjs.org/headers
    - nodejs_version: 12
      platform: x86
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 9.0.5
      TOOLSET_ARGS: --dist-url=https://electronjs.org/headers

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
